CREATE TABLE alunos
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    responsavel_id  BIGINT,
    nome            VARCHAR(255)                            NOT NULL,
    email           VARCHAR(255)                            NOT NULL,
    matricula       VARCHAR(255)                            NOT NULL,
    data_nascimento date                                    NOT NULL,
    status          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_alunos PRIMARY KEY (id)
);

CREATE TABLE disciplinas
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    responsavel_id BIGINT,
    codigo         VARCHAR(255)                            NOT NULL,
    nome           VARCHAR(255)                            NOT NULL,
    carga_horaria  INTEGER                                 NOT NULL,
    semestre       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_disciplinas PRIMARY KEY (id)
);

CREATE TABLE matriculas
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    responsavel_id BIGINT,
    aluno_id       BIGINT                                  NOT NULL,
    disciplina_id  BIGINT                                  NOT NULL,
    data_matricula date                                    NOT NULL,
    situacao       VARCHAR(255)                            NOT NULL,
    nota_final     DOUBLE PRECISION,
    CONSTRAINT pk_matriculas PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    responsavel_id BIGINT,
    login          VARCHAR(255)                            NOT NULL,
    senha          VARCHAR(255)                            NOT NULL,
    perfil         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE alunos
    ADD CONSTRAINT uc_alunos_matricula UNIQUE (matricula);

ALTER TABLE disciplinas
    ADD CONSTRAINT uc_disciplinas_codigo UNIQUE (codigo);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_login UNIQUE (login);

ALTER TABLE matriculas
    ADD CONSTRAINT uk_matricula_aluno_disciplina UNIQUE (aluno_id, disciplina_id);

CREATE UNIQUE INDEX idx_codigo ON disciplinas (codigo);

CREATE UNIQUE INDEX idx_login ON usuarios (login);

CREATE UNIQUE INDEX idx_matricula ON alunos (matricula);

ALTER TABLE alunos
    ADD CONSTRAINT FK_ALUNOS_ON_RESPONSAVEL FOREIGN KEY (responsavel_id) REFERENCES usuarios (id);

ALTER TABLE disciplinas
    ADD CONSTRAINT FK_DISCIPLINAS_ON_RESPONSAVEL FOREIGN KEY (responsavel_id) REFERENCES usuarios (id);

ALTER TABLE matriculas
    ADD CONSTRAINT FK_MATRICULAS_ON_ALUNO FOREIGN KEY (aluno_id) REFERENCES alunos (id);

ALTER TABLE matriculas
    ADD CONSTRAINT FK_MATRICULAS_ON_DISCIPLINA FOREIGN KEY (disciplina_id) REFERENCES disciplinas (id);

ALTER TABLE matriculas
    ADD CONSTRAINT FK_MATRICULAS_ON_RESPONSAVEL FOREIGN KEY (responsavel_id) REFERENCES usuarios (id);

ALTER TABLE usuarios
    ADD CONSTRAINT FK_USUARIOS_ON_RESPONSAVEL FOREIGN KEY (responsavel_id) REFERENCES usuarios (id);
